services:
  _defaults:
    autowire: true
    autoconfigure: false

  Raisaev\UzTicketsParser\:
    resource: '../src/*'
    exclude: '../src/{Entity,Filter}'

  Raisaev\UzTicketsParser\Rest\Client:
    shared: false

  Symfony\Component\Cache\Adapter\FilesystemAdapter:
    arguments:
      $directory: '../var/cache/'
